# Generated by Django 4.2.1 on 2023-05-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dep', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(max_length=50, unique=True)),
                ('direcicion_dep', models.CharField(max_length=50)),
                ('descripcion_dep', models.TextField()),
                ('valordiario_dep', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inventario_dep', models.TextField()),
                ('estado_dep', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_comienzo', models.DateField()),
                ('fecha_final', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('advance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_id_dep', to='app.departamento')),
                ('nombre_dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva_nombre_dep', to='app.departamento', to_field='nombre_dep')),
            ],
        ),
    ]
