# Generated by Django 4.2.1 on 2023-05-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clientes', models.CharField(max_length=50, unique=True)),
                ('rut_clientes', models.CharField(max_length=50, unique=True)),
                ('email_clientes', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
