# Generated by Django 4.2.1 on 2023-05-28 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='email_clientes',
            new_name='email_cliente',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='nombre_clientes',
            new_name='nombre_cliente',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='rut_clientes',
            new_name='rut_cliente',
        ),
    ]
