# Generated by Django 4.2.1 on 2023-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_email_clientes_clientes_email_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='departamentos'),
        ),
    ]
