# Generated by Django 4.2.1 on 2023-05-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_departamento_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='direcicion_dep',
            new_name='direccion_dep',
        ),
    ]
