# Generated by Django 4.2.1 on 2023-05-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_direcicion_dep_departamento_direccion_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='advance',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
