# Generated by Django 4.2.1 on 2023-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reserva_advance_alter_reserva_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='valordiario_dep',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='advance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
