# Generated by Django 4.2.1 on 2023-05-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_departamento_valordiario_dep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='valordiario_dep',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='advance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
