# Generated by Django 4.2.1 on 2023-05-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado_dep',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ImagenDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='departamentos')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamento')),
            ],
        ),
    ]
