# Generated by Django 4.2.1 on 2023-05-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_departamento_estado_dep_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiciosExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('wifi', models.BooleanField(default=False)),
                ('reseñas', models.TextField(blank=True)),
            ],
        ),
    ]
