# Generated by Django 4.2.1 on 2023-05-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_departamento_estado_dep_imagendepartamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendepartamento',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='app.departamento'),
        ),
    ]
