# Generated by Django 4.2.1 on 2023-05-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_imagendepartamento_departamento'),
        ('app', '0011_serviciosextra'),
    ]

    operations = [
    ]
