# Generated by Django 4.2.1 on 2023-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20230529_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='ciudad_dep',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
