# Generated by Django 4.2.1 on 2023-06-28 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='advance',
            new_name='avance',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_comienzo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_final',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='id_dep',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre_dep',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='precio',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cant_dias',
            field=models.SmallIntegerField(default=1, verbose_name='Cantidad de dias a reservar'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.departamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
