# Generated by Django 4.2.1 on 2023-06-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_reserva_departamento_alter_reserva_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.RemoveField(
            model_name='serviciosextra',
            name='reseñas',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='departamento',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicio_extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serviciosextra'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tour'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(blank=True, max_length=10, verbose_name='Rut'),
        ),
    ]
